# ============================================
# APPLICATION CONFIGURATION (PROD)
# ============================================
spring.application.name=users-service
server.port=8082

# ============================================
# SUPABASE / POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://db.ninfjedrwxaezrhslvod.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Emsi2025//@
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE (POSTGRESQL)
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# PROD SAFETY
# ============================================
spring.sql.init.mode=never
spring.h2.console.enabled=false

# ============================================
# EUREKA CLIENT
# ============================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
