spring.application.name=notification-service
spring.profiles.active=default
spring.cloud.config.uri=http://localhost:8888
# Les propriétés spécifiques sont maintenant centralisées dans le config server.
