spring.application.name=users-service

server.port=8082

spring.datasource.url=jdbc:h2:mem:users-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console (pour voir la BD dans le navigateur)"khoti bd H2 o salam"
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.config.import=optional:configserver:http://localhost:8888