server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:

        # ROUTE Users Service
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**

        # ROUTE Inscription Service
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/**

        # ROUTE Soutenance Service
        - id: stadium-service
          uri: lb://STADIUM-SERVICE
          predicates:
            - Path=/stadium/**


  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
