spring.application.name=gateway-service
spring.profiles.active=default
spring.cloud.config.uri=http://localhost:8888
# Les propri�t�s sp�cifiques sont maintenant centralis�es dans le config server.
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
