
spring.application.name=inscription-service

# SUPABASE / POSTGRESQL CONFIGURATION
spring.datasource.url=jdbc:postgresql://db.ninfjedrwxaezrhslvod.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE (POSTGRESQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Port par défaut
server.port=8083
