# ============================================
# APPLICATION CONFIGURATION
# Activer avec : spring.profiles.active=supabase
# ============================================
spring.config.activate.on-profile=supabase
spring.application.name=stadium-service
server.port=8083

# ============================================
# SUPABASE / POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://db.ninfjedrwxaezrhslvod.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=VOTRE_MOT_DE_PASSE
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# DÉSACTIVER H2 ET SQL INIT EN PROD
# ============================================
spring.sql.init.mode=never
spring.h2.console.enabled=false

# ============================================
# EUREKA CLIENT
# ============================================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
