<<<<<<< HEAD
# APPLICATION CONFIGURATION (PROD)
# ============================================
# ============================================
# APPLICATION CONFIGURATION (PROD)
# ============================================
spring.application.name=users-service
server.port=8082

# ============================================
# APPLICATION CONFIGURATION (PROD)
# ============================================
spring.application.name=stadium-service
server.port=8083
=======
# ============================================
# APPLICATION CONFIGURATION
# Activer avec : spring.profiles.active=supabase
# ============================================
spring.config.activate.on-profile=supabase
spring.application.name=stadium-service
server.port=8083

>>>>>>> c1a8c4615fd4644e3bd94f4fbcd4c57c6a7b417e
# ============================================
# SUPABASE / POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://db.ninfjedrwxaezrhslvod.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=Emsi2025//@
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE (POSTGRESQL)
=======
spring.datasource.password=VOTRE_MOT_DE_PASSE
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE
>>>>>>> c1a8c4615fd4644e3bd94f4fbcd4c57c6a7b417e
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ============================================
<<<<<<< HEAD
# PROD SAFETY
=======
# DÉSACTIVER H2 ET SQL INIT EN PROD
>>>>>>> c1a8c4615fd4644e3bd94f4fbcd4c57c6a7b417e
# ============================================
spring.sql.init.mode=never
spring.h2.console.enabled=false

# ============================================
# EUREKA CLIENT
# ============================================
<<<<<<< HEAD
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
=======
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
>>>>>>> c1a8c4615fd4644e3bd94f4fbcd4c57c6a7b417e
eureka.instance.prefer-ip-address=true
