# ============================================
# PROFIL SUPABASE (PRODUCTION)
# Activer avec : spring.profiles.active=supabase
# ============================================
spring.config.activate.on-profile=supabase

# ============================================
# SUPABASE / POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://db.ninfjedrwxaezrhslvod.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Emsi2025//@   # Remplace par ton vrai mot de passe Supabase si différent
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE (POSTGRESQL)
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Désactiver H2 et SQL init en prod
spring.sql.init.mode=never
spring.h2.console.enabled=false
