spring.application.name=eureka-service
spring.profiles.active=default
spring.cloud.config.uri=http://localhost:8888
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# Les propriétés spécifiques sont maintenant centralisées dans le config server.
